services:
  - type: web
    name: movie-recommender
    env: python
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true